# Generated by Django 3.2.9 on 2021-11-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
