# Generated by Django 3.2.9 on 2021-11-09 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
