# Generated by Django 3.2.9 on 2021-11-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_auto_20211109_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='associated_with_drug_resistance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='impact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='protein_effect',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='variant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='variant_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
