# Generated by Django 3.2.9 on 2021-11-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, max_length=200, null=True)),
                ('associated_with_drug_resistance', models.CharField(blank=True, max_length=200, null=True)),
                ('protein_effect', models.CharField(blank=True, max_length=200, null=True)),
                ('impact', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gene.genes')),
            ],
        ),
    ]
