# Generated by Django 3.2.9 on 2021-11-09 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('impact', models.CharField(blank=True, max_length=200, null=True)),
                ('variant_description', models.CharField(blank=True, max_length=200, null=True)),
                ('variant', models.CharField(blank=True, max_length=200, null=True)),
                ('associated_with_drug_resistance', models.CharField(blank=True, max_length=200, null=True)),
                ('protein_effect', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='genes',
            old_name='impact',
            new_name='gene',
        ),
        migrations.AddField(
            model_name='genes',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
